.github/workflows/deploy.yaml
This PR set a GH workflow to trigger a commit on develop and run a deploy to GHpages
=> GH Action for deploy on GHpages

.storybook/preview.js, src/components/Feature/Feature.tsx, src/components/Feature/FeatureStackItem.tsx, src/components/Feature/Subtitle.tsx, src/stories/Feature/dark.stories.tsx, src/stories/Feature/featureCommons.tsx, src/stories/Feature/light.stories.tsx
=> [EDCO-22] [EDCO-23] Feature Component fix

.github/workflows/publish_to_npm.yml, package.json, src/types/index.d.ts, tsconfig.json
There are some modifications to the package.json and files to set the correct path&env for a correct publishing on npm.
=> [#EDCO-24]  Code's tuning to publish on npm

src/stories/Form/dark.stories.tsx, src/stories/Form/light.stories.tsx, src/types/index.d.ts
=> [EDCO-18] Storybook form stories

.github/workflows/publish_to_npm.yml
This PR  tries to add two new control's fields to enhance the control over the publish pipeline
=> Add more control to the pipeline

src/components/BannerLink/BannerLink.tsx
This PR fix a typescript compilation error in the Banner Link Component
=> feat: Banner Link Component, typescript error fixed

.github/workflows/publish_to_npm.yml, package.json
This PR seems to fix a trouble with the build of the npm module
=> Publish to npm empty module bug

src/index.ts
Export missing components from the index.ts file.
Fixes # (edco-25)
=> [EDCO-25] Components Export

src/components/Header/components/MenuDropdown.tsx, src/stories/Header/defaults.tsx
Header menu accepts href as prop.
Fixes # (edco-27)
=> [EDCO-27]: Header Links

src/components/Header/Header.tsx
Header resize listener fix
Fixes # (edco-29)
=> [EDCO-29] Header resize fix

src/components/Hero.tsx, src/stories/Hero/dark.stories.tsx, src/stories/Hero/light.stories.tsx
Hero background prop can be a string or a react element.
Fixes # (edco-31)
=> [EDCO-31] Hero Background Element

.github/dependabot.yml
Add a conf file for _dependabot_ checker
=> [#EDCO-33] Added dependabot configuration

src/components/EContainer.tsx, src/components/Editorial/Editorial.tsx, src/components/Feature/Feature.tsx, src/components/Feature/FeatureStackItem.tsx, src/components/Hero.tsx, src/components/HowTo/HowTo.tsx, src/stories/Hero/dark.stories.tsx, src/stories/Hero/light.stories.tsx
This PR fixes some spacing and alignment issues
=> [CPP-85] General feedbacks

src/components/EContainer.tsx, src/components/Editorial/Editorial.tsx
Padding and alignment for the editorial components.
Fixes # [edco-35](https://pagopa.atlassian.net/jira/software/projects/EDCO/boards/398?selectedIssue=EDCO-35)
=> [EDCO-35] Editorial styles fix

src/components/BannerLink/BannerLink.tsx, src/components/DialogBubble.tsx, src/components/Feature/FeatureStackItem.tsx, src/components/Footer/Footer.tsx, src/components/Footer/LangSwitch.tsx, src/components/Header/Header.tsx, src/components/Header/components/HamburgerMenu.tsx, src/components/Header/components/Navigation.tsx, src/components/Hero.tsx, src/components/HowTo/HowToStep.tsx
Improved accessibility using semantic html landmarks and aria attributes.
Fixes # [edco-40](https://pagopa.atlassian.net/browse/EDCO-40)
=> [EDCO-40] Accessibilità

src/components/PhotoVideo/YouTube.tsx, src/components/PhotoVideo/index.tsx, src/stories/PhotoVideo/photoVideo.stories.tsx, src/types/index.d.ts, src/utils/index.ts
this PR extends the photoVideo component. Now it's possibile to use standard html5 video with the youtube layout
Fixes # [edco-44](https://pagopa.atlassian.net/browse/EDCO-44)
=> [EDCO-44[: photoVideo component, using html5 video tag

src/components/PhotoVideo/YouTube.tsx, src/components/PhotoVideo/index.tsx, src/stories/PhotoVideo/photoVideo.stories.tsx
Added the property playsInLine to the video tag, that should enable the autoplay functionality on the latest ios safari browser
=> playsInLine property added to video tag

src/components/Hero/index.tsx, src/components/Text/index.tsx, src/index.ts, src/stories/Text/text.stories.tsx
With this PR the Text Editorial component is added to the library
Fixes # [EDCO-49](https://pagopa.atlassian.net/browse/EDCO-49)
[EDCO-49]: https://pagopa.atlassian.net/browse/EDCO-49?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [EDCO-49] Text component 

src/components/Download/index.tsx, src/index.ts, src/stories/Download/dark.stories.tsx, src/stories/Download/ligth.stories.tsx, src/stories/assets/sample.pdf, src/types/index.d.ts
With this PR the Download Editorial component is added to the library
=> [EDCO-10] Download component

src/components/Cards/index.tsx, src/components/Cards/item.tsx, src/stories/Cards/dark.stories.tsx, src/stories/Cards/ligth.stories.tsx
With this PR the Cards Editorial component is added to the library
Fixes # [EDCO-07](https://pagopa.atlassian.net/browse/EDCO-07)
=> [EDCO-07] Cards component 

README.md
- storybook [link](http://pagopa.github.io/pagopa-editorial-components) added
- some references updated
P.S.: Please, make note that the storybook link could be not yet available
Fixes # [EDCO-52](https://pagopa.atlassian.net/browse/EDCO-52)
[EDCO-52]: https://pagopa.atlassian.net/browse/EDCO-52?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [EDCO-52] Readme updated

.github/workflows/deploy.yaml
Update to trigger with the main branch
This PR updates the GH Action to trigger-it using the `main` branch and optionally a manual starts
=> Update action to trigger manual.

.husky/commit-msg, .husky/pre-commit, .husky/prepare-commit-msg, .lintstagedrc, commitlint.config.js, package.json, yarn.lock
changes that improve the developer experience
- adds lint-staged package and configuration file
- adds husky package and configuration file
- add commitlint package and configuration
=> [EDCO-57] lint-staged, husky and commitlint

.github/workflows/deploy.yaml
This PR updates the yaml file to deploy on GHpages using another action.
=> ci: update action to deploy on GHpages

.github/workflows/deploy.yaml
Update to 18 the GHAction to build the main site on the GHPages
=> chore: update node to 18 in the action conf

.github/workflows/pre-release.yaml, CHANGELOG.md, release.config.js
This pr introduces a new pattern for releasing new versions. 
It requires that a release type branch is created and that a pr is subsequently requested towards the main branch.
On release type branch a new version is calculated automatically by the commit messages.
On the main branch a new version is automatically published to NPM registry
=> New Release Pattern

.github/workflows/deploy.yaml, .github/workflows/pre-release.yaml, .github/workflows/publish_to_npm.yml, .github/workflows/release.yaml, CHANGELOG.md, package.json
Should fix a problem with husky and postinstall script
- Node version updated in several files (package.json, github action files)
- Postinstall script removed from package.json file (run prepare instead manually)
[x] patch
[] minor
[] major
=> Release 2.1.2

src/components/Accordion/Accordion.tsx, src/components/EIcon.tsx, src/components/Footer/components/FooterColumn.tsx, src/components/HowTo/HowTo.tsx, src/components/Quote/Quote.tsx, src/components/StripeLink.tsx, src/stories/Abstract/abstractCommons.tsx
Fixes some of the accessibility problems found by the storybook test runner
- Accordion: title is not rendered if missing
- HowTo: title is not rendered if missing
- Footer: social icons have aria-labels passed to the link wrapping them
- Quote: back and forward arrows aria-label
- StripeLink: default aria-label for icon only button
- Abstract: added alt text to stories background images
1. Testing with storybook test runner
```bash
yarn test-storybook # no accessbility problems are found for the above components
```
2. Checking the components Accessibilty tab plugin in a running storybook instance
=> [EDCO-62] Accessibility fixes

src/index.ts
Fixing the three new imports that were missing the "./" on the starting path.
- Fixing paths of new integrated components.
Imports in the index file will be tested once in production, they're only imports.
=> fix: missing "./" for the three imports

CHANGELOG.md, package.json, src/components/Accordion/Accordion.tsx, src/components/BannerLink/Content.tsx, src/components/Editorial/Editorial.tsx, src/components/Header/Header.tsx, src/components/Header/components/MenuDropdown.tsx, src/components/StripeLink.tsx
Those changes are required to fix two bugs and some layouts problems occurred while using EC on B2BP
- Fixed layout for Accordion component
- Fixed Bannerlink HTML rendering bug 
- Fixed StripeLink HTML rendering bug
- Fixed wrong mobile layout on Editorial
- Fixed Header padding
- Fixed MenuDropdown border bottom
Tested on the Storybook. Then builded and tested on B2BP
=> Fix: Editorial-Components hotfix

CHANGELOG.md, package.json, src/components/Cards/index.tsx, src/components/Cards/item.tsx
Those changes are required to align "Cards" component to SEND legacy version.
- Added an optional Button to Cards component
- Changed "Text" props from required to optional
- Changed "link" to an array of elements
Tested on the Storybook. Then builded and tested on B2BP
=> fix: cards interface changes [B2BP-411]

CHANGELOG.md, package.json, src/components/Editorial/Editorial.tsx, src/components/Hero/index.tsx
Changed the useState(window.innerWidth <= 1024) to typeof window !== 'undefined' ? window.innerWidth <= 1024 : false in order to fix the issue about window while using the component on B2BP
- Changed the Editorial.tsx file
Tested in local running the storybook. Then builded and passed the "dist" folder inside the B2BP project.
=> fix: Editorial window error [B2BP-461]

CHANGELOG.md, package.json, src/components/BannerLink/Content.tsx, src/components/HowTo/HowToStep.tsx
This PR will fix small changes on the variant H from two components: BannerLink and HowTo
- Changed variant on Content.tsx from BannerLink component
- Changed variant on HowToStep.tsx from HowTo component
Tested in local running the storybook. Then builded and passed the "dist" folder inside the B2BP project.
=> fix: [B2BP-494] - small Ui fix

CHANGELOG.md, package.json, src/components/Hero/index.tsx, src/stories/Hero/dark.stories.tsx, src/stories/Hero/light.stories.tsx
This PR will fix the "small" size for the "Hero" component
- Added a new size for "Hero" component in "index.tsx" file
- Fixed style for the new size added
- Updated Storybook
Tested in local running the storybook. Then builded and passed the "dist" folder inside the B2BP project.
=> fix: [B2BP-428] - "Hero" component fix on small size
